name: network-policies
namespace: daniel-lopez-fisag-dev

# Dummy values to avoid template errors
image:
  repository: dummy
  tag: dummy
replicas: 0

# Disable all microservice components
service:
  enabled: false
route:
  enabled: false
hpa:
  enabled: false
statefulset:
  enabled: false

# Enable network policies
networkPolicies:
  enabled: true
